name: Node.js Discord Bot CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  lint:
    name: Lint and Audit
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint || echo "No lint script"
      - name: NPM Audit
        run: npm audit --audit-level=high

  local-run-sanity:
    name: Local run dry-run
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Dry-run local bot
        env:
          CI: true
        run: |
          chmod +x scratch/shared/infra/scripts/local_run_discord_bot.sh
          scratch/shared/infra/scripts/local_run_discord_bot.sh --dry-run
