openapi: 3.0.0
info:
  title: JokeGen Batch API (MVP v2)
  version: 0.0.0
paths:
  /api/jokes/batches:
    post:
      summary: Create a new batch of jokes
      operationId: createJokeBatch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                batchSize:
                  type: integer
                  description: Number of jokes to generate (1-1000)
                prompts:
                  type: array
                  items:
                    type: string
              required:
                - batchSize
      responses:
        '202':
          description: Batch accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  batchId:
                    type: string
                  status:
                    type: string
                  total:
                    type: integer
  /api/jokes/batches/{batchId}/status:
    get:
      summary: Get batch status
      operationId: getBatchStatus
      parameters:
        - name: batchId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Batch status
          content:
            application/json:
              schema:
                type: object
                properties:
                  batchId:
                    type: string
                  status:
                    type: string
                  total:
                    type: integer
                  createdIds:
                    type: array
                    items:
                      type: integer
                  startedAt:
                    type: string
                  completedAt:
                    type: string
                  error:
                    type: string
components:
  schemas:
    Joke:
      type: object
      properties:
        id:
          type: integer
        setup:
          type: string
        punchline:
          type: string
        category:
          type: string
        author:
          type: string
        created_at:
          type: string
